
name : test

on:

    workflow_dispatch:

    pull_request:

        branches : [ main ]

    push:

        branches : [ main ]


jobs:

    test:

        runs-on : [ ubuntu-latest , windows-latest , macos-latest ]

        steps:

            -   name : Checkout Repository
                uses : actions/checkout@v3

            -   name : Setup News
                uses : ./
                with :

