
name : Update News Sections

on:

    workflow_dispatch:

    pull_request:

        branches : [ main ]

        paths :

            -   'Example/**'

    push:

        branches : [ main ]

        paths :

            -   'Example/**'


concurrency:

    cancel-in-progress : true
    group : news


jobs:

    Action_Test:

        runs-on : ubuntu-latest

        steps:

            -   name : Checkout Repository
                uses : actions/checkout@v3

            -   name : Setup News
                uses : ./
                with :

                    config : .github/.News.yml

            -   name : Commit Changes
                uses : EndBug/add-and-commit@v9
                with :

                    default_author : github_actor
                    message : Updated News Sections
                    add : README.md
