
name : test

on:

    workflow_dispatch:

    pull_request:

        branches : [ main ]

        paths :

            -   'Example/**'

    push:

        branches : [ main ]

        paths :

            -   'Example/**'



jobs:

    Action_Test:

        runs-on : ubuntu-latest

        steps:

            -   name : Checkout Repository
                uses : actions/checkout@v3

            -   name : Setup News
                uses : ./
                with :

                    config : .github/.News.yml
